server:
  port: 10022
  servlet:
    context-path: /security
spring:
  mvc:
    view:
      suffix: .html
      prefix: templates/
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/

